[package]
name = "esp32-iot-monitor"
version = "0.1.0"
edition = "2021"
description = "Micro embedded-sys for esp32-iot"
license = "CC0 1.0"

[dependencies]
esp-idf-hal = "0.35.0"   
esp-wifi = "0.6.0"
serde = { version = "1.0", features = ["derive"] } 
serde_json = "1.0"       
embassy-executor = "0.7.0" 
embassy-sync = "0.6.2"   
form_urlencoded = "1.2.1"
postcard = "1.0"
embedded-svc = "0.23"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[features]
default = ["std"]
std = []
