[build]
target = "xtensa-esp32-espidf"

[unstable]
build-std = ["core", "compiler_builtins"]

[target.xtensa-esp32-espidf]
runner = "espflash"
rustflags = [
    "-C", "link-arg=-Tesp32.common.ld",
    "-C", "link-arg=-Tesp32.rom.ld",
    "-C", "link-arg=-Tesp32.sections.ld",
    "-C", "link-arg=-Tesp32.peripherals.ld"
]
